name: nber-workflow
recipe: drupal8
config:
  webroot: .
  drush: global:8.1.15
  drupal: true
  xdebug: true
services:
  appserver:
    run:
      - "cd $LANDO_MOUNT && composer install"
      - "cd $LANDO_MOUNT && drush si standard --config-dir=sites/default/files/config_fkIr-vCzuRh-3g9BrfnYSLZyywBsJyHlBsPGt4oZd1FNVx2BWfjFuHEoS6pLqw12GFAHpfpDkg/sync/ --account-name=admin --account-pass=admin -y"
